export const POKEMON_NATURES = [
    { name: "Adamant", plus: "Atk", minus: "SpA" },
    { name: "Bashful", plus: null, minus: null },
    { name: "Bold", plus: "Def", minus: "Atk" },
    { name: "Brave", plus: "Atk", minus: "Spe" },
    { name: "Calm", plus: "SpD", minus: "Atk" },
    { name: "Careful", plus: "SpD", minus: "SpA" },
    { name: "Docile", plus: null, minus: null },
    { name: "Gentle", plus: "SpD", minus: "Def" },
    { name: "Hardy", plus: null, minus: null },
    { name: "Hasty", plus: "Spe", minus: "Def" },
    { name: "Impish", plus: "Def", minus: "SpA" },
    { name: "Jolly", plus: "Spe", minus: "SpA" },
    { name: "Lax", plus: "Def", minus: "SpD" },
    { name: "Lonely", plus: "Atk", minus: "Def" },
    { name: "Mild", plus: "SpA", minus: "Def" },
    { name: "Modest", plus: "SpA", minus: "Atk" },
    { name: "Naive", plus: "Spe", minus: "SpD" },
    { name: "Naughty", plus: "Atk", minus: "SpD" },
    { name: "Quiet", plus: "SpA", minus: "Spe" },
    { name: "Quirky", plus: null, minus: null },
    { name: "Rash", plus: "SpA", minus: "SpD" },
    { name: "Relaxed", plus: "Def", minus: "Spe" },
    { name: "Sassy", plus: "SpD", minus: "Spe" },
    { name: "Serious", plus: null, minus: null },
    { name: "Timid", plus: "Spe", minus: "Atk" }
];
